version: "3.7"

services:

  web:
    image: nginx:latest
    ports:
      - "8060:80"

    volumes:
      - ./code:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:fpm
    volumes:
      - ./code:/code
