version: "3.7"

services:

  web:
    image: nginx:latest
    container_name: nginx-webserver
    restart: always
    ports:
      - "8060:80"

    volumes:
      - ./code:/code
      - ./env:/env
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:fpm
    container_name: php-webserver
    restart: always
    volumes:
      - ./code:/code
